Repository tim-master2020/UKS, pull requests merged in 2021-02, with the labels that each got.

#22 Change user model
  github/comment/models.py
  github/commit/models.py
  github/task/models.py
  github/user/models.py
Labels: backend, feature

#23 Implement CRUD operations for Repository entity
  github/github/templates/repository/addRepository.html
  github/github/templates/repository/allRepositories.html
  github/github/templates/repository/detailRepository.html
  github/github/urls.py
  github/repository/forms.py
  github/repository/url.py
  github/repository/views.py
Labels: backend, feature, frontend

#24 Registration functionality
  github/github/templates/registration/registration.html
  github/github/urls.py
  github/github/views.py
  github/user/models.py
Labels: backend, feature, frontend

#26 Changed wiki's relationship.
  github/project/models.py
  github/repository/models.py
Labels: backend

#27 Login functionality
  github/github/settings.py
  github/github/templates/landing/landing.html
  github/github/templates/navbar.html
  github/github/templates/registration/login.html
  github/github/urls.py
  github/github/views.py
Labels: backend, feature, frontend

#29 Feature update one to one relationships
  github/branch/migrations/0001_initial.py
  github/comment/migrations/0001_initial.py
  github/comment/migrations/0002_comment_task.py
  github/comment/migrations/0003_comment_user.py
  github/commit/migrations/0001_initial.py
  github/commit/migrations/0002_commit_user.py
  github/label/migrations/0001_initial.py
  github/milestone/migrations/0001_initial.py
  github/project/migrations/0001_initial.py
  github/repository/migrations/0001_initial.py
  github/task/migrations/0001_initial.py
  github/task/migrations/0002_auto_20210129_1624.py
  github/task/migrations/0003_task_asignees.py
  github/task/models.py
  github/user/migrations/0001_initial.py
  github/wiki/migrations/0001_initial.py
Labels: backend, feature

#32 Bugfix repository missing user field
  github/repository/models.py
  github/repository/views.py
Labels: backend, bug, frontend

#34 Create master branch when new repository is added
  github/repository/views.py
Labels: backend, bug

#35 Feature label crud
  github/github/templates/base.html
  github/github/templates/label/add-label.html
  github/github/templates/label/all-labels.html
  github/github/templates/label/delete-label.html
  github/github/templates/label/render-labels.html
  github/github/templates/label/update-label.html
  github/github/templates/repository/detailRepository.html
  github/github/urls.py
  github/label/admin.py
  github/label/forms.py
  github/label/urls.py
  github/label/views.py
  github/repository/views.py
Labels: backend, frontend

#37 Imporvement adding repository should be modal not a new page
  github/github/templates/repository/addRepository.html
  github/github/templates/repository/allRepositories.html
Labels: frontend, improvment

#38 Feature wiki crud
  github/github/templates/repository/detailRepository.html
  github/github/templates/wiki/wiki.html
  github/github/urls.py
  github/repository/forms.py
  github/repository/models.py
  github/repository/views.py
  github/wiki/forms.py
  github/wiki/models.py
  github/wiki/url.py
  github/wiki/views.py
Labels: backend, feature

#42 Added new cookie limit
  github/github/settings.py
Labels: backend

#45 Add task repo and project relationships
  github/github/templates/repository/repoTabs.html
  github/task/models.py
Labels: backend

#47 Change milestone-task relationship
  github/task/models.py
Labels: backend, bug

#48 Feature project crud
  github/github/templates/project/addProject.html
  github/github/templates/project/allProjects.html
  github/github/templates/project/deleteProject.html
  github/github/templates/project/updateProject.html
  github/github/templates/repository/detailRepository.html
  github/github/urls.py
  github/project/forms.py
  github/project/urls.py
  github/project/views.py
  github/repository/views.py
Labels: backend, feature, frontend

#49 Added sign out button restriction
  github/github/templates/navbar.html
Labels: frontend

#51 Updated milestone's relationships.
  github/milestone/models.py
Labels: backend, improvment

#52 Feature milestione crud
  github/github/templates/milestone/addMilestone.html
  github/github/templates/milestone/allMilestones.html
  github/github/templates/milestone/deleteMilestone.html
  github/github/templates/milestone/updateMilestone.html
  github/github/templates/repository/detailRepository.html
  github/github/urls.py
  github/milestone/forms.py
  github/milestone/urls.py
  github/milestone/views.py
  github/repository/views.py
Labels: backend, feature, frontend

#54 changed task and milestone relationship
  github/task/models.py
Labels: backend

#56 Improvement add members to repository
  github/github/templates/repository/addRepository.html
  github/repository/models.py
  github/repository/views.py
Labels: backend, frontend, improvment

#58 Improvement of registration and login form
  github/github/templates/registration/login.html
  github/github/templates/registration/registration.html
  github/github/views.py
  github/user/forms.py
  github/user/models.py
Labels: frontend, improvment

#59 Feature task crud
  github/github/settings.py
  github/github/templates/repository/detailRepository.html
  github/github/templates/repository/repoTabs.html
  github/github/templates/task/all-tasks.html
  github/github/templates/task/delete-task.html
  github/github/templates/task/detail-task.html
  github/github/templates/task/render-tasks.html
  github/github/urls.py
  github/repository/views.py
  github/task/forms.py
  github/task/models.py
  github/task/urls.py
  github/task/views.py
Labels: backend, frontend

#61 Improvment design wiki project
  github/github/templates/project/allProjects.html
  github/github/templates/project/deleteProject.html
  github/github/templates/project/updateProject.html
  github/github/templates/repository/repoTabs.html
  github/github/templates/wiki/allWiki.html
Labels: frontend, improvment

#64 added return value in models.
  github/milestone/models.py
  github/project/models.py
  github/wiki/models.py
Labels: backend, improvment

#65 Add tasks to project
  github/github/templates/project/allProjects.html
  github/github/templates/project/detailProject.html
  github/project/forms.py
  github/project/urls.py
  github/project/views.py
Labels: backend, feature, frontend

#67 Create adding milestone to project.
  github/github/templates/milestone/milestonesInProject.html
  github/github/templates/project/allProjects.html
  github/github/templates/project/detailProject.html
  github/github/templates/task/task-in-project.html
  github/project/urls.py
  github/project/views.py
  github/task/models.py
Labels: backend, feature, frontend

#68 Feature comment crud
  github/comment/admin.py
  github/comment/forms.py
  github/comment/urls.py
  github/comment/views.py
  github/github/templates/comments/create-comment.html
  github/github/templates/comments/delete-comment.html
  github/github/templates/comments/edit-comment.html
  github/github/templates/comments/render-comments.html
  github/github/templates/task/detail-task.html
  github/github/urls.py
  github/task/views.py
Labels: backend, frontend

#70 Improvement label forms
  github/github/templates/label/add-label.html
  github/github/templates/label/all-labels.html
  github/github/templates/label/delete-label.html
  github/github/templates/label/render-labels.html
  github/github/templates/label/update-label.html
  github/label/forms.py
  github/repository/views.py
Labels: backend, frontend

#72 Implemented adding profile picture.
  github/github/settings.py
  github/github/templates/navbar.html
  github/github/templates/photo/addPhoto.html
  github/github/templates/profile/profile.html
  github/github/templates/profile/update.html
  github/github/urls.py
  github/github/views.py
  github/photo/__init__.py
  github/photo/admin.py
  github/photo/apps.py
  github/photo/forms.py
  github/photo/migrations/__init__.py
  github/photo/models.py
  github/photo/tests.py
  github/photo/urls.py
  github/photo/views.py
  github/user/forms.py
  github/user/urls.py
  github/user/views.py
Labels: backend, feature, frontend

#73 Feature branch crud
  github/branch/forms.py
  github/branch/url.py
  github/branch/views.py
  github/github/templates/branch/addBranch.html
  github/github/templates/branch/allBranches.html
  github/github/templates/branch/detailBranch.html
  github/github/templates/repository/repoTabs.html
  github/github/urls.py
  github/repository/views.py
Labels: backend, feature, frontend

#75 Feature commit crud
  github/branch/views.py
  github/commit/forms.py
  github/commit/models.py
  github/commit/urls.py
  github/commit/views.py
  github/github/templates/branch/allBranches.html
  github/github/templates/branch/detailBranch.html
  github/github/templates/commits/addCommit.html
  github/github/templates/commits/allCommits.html
  github/github/urls.py
Labels: backend, feature, frontend

#77 Feature create branch from another
  github/branch/models.py
  github/branch/url.py
  github/branch/views.py
  github/github/templates/branch/allBranches.html
  github/github/templates/branch/newBranch.html
Labels: backend, feature, frontend

#78 Fix common error when adding a repository
  github/repository/views.py
Labels: backend, bug, frontend

#80 Created Home page for logged in user.
  github/github/templates/landing/landing.html
  github/github/templates/navbar.html
  github/github/templates/repository/repositoriesHomePage.html
  github/github/views.py
Labels: backend, feature, frontend

#84 Bugfix photo filter and url
  github/github/views.py
  github/photo/models.py
Labels: backend

#85 Improvement task assignes
  github/github/templates/task/render-tasks.html
  github/repository/views.py
Labels: backend, frontend

#87 Replaced absolute url paths with relative paths.
  github/github/templates/branch/allBranches.html
  github/github/templates/project/allProjects.html
  github/github/templates/repository/addRepository.html
  github/github/templates/repository/allRepositories.html
  github/github/templates/repository/detailRepository.html
  github/github/templates/wiki/allWiki.html
  github/github/templates/wiki/wiki.html
Labels: bug, frontend

#89 Bugfix task mandatory fields
  github/github/templates/task/render-tasks.html
  github/task/models.py
Labels: bug

#90 Improvement app frontend
  github/github/templates/base.html
  github/github/templates/branch/allBranches.html
  github/github/templates/label/all-labels.html
  github/github/templates/label/delete-label.html
  github/github/templates/label/update-label.html
  github/github/templates/milestone/allMilestones.html
  github/github/templates/milestone/deleteMilestone.html
  github/github/templates/milestone/updateMilestone.html
  github/github/templates/project/allProjects.html
  github/github/templates/project/deleteProject.html
  github/github/templates/project/updateProject.html
  github/github/templates/repository/allRepositories.html
  github/github/templates/task/all-tasks.html
  github/github/templates/task/detail-task.html
  github/github/templates/wiki/allWiki.html
Labels: frontend, improvment

#92 Fixed branch delete api.
  github/github/templates/branch/allBranches.html
Labels: backend, bug, frontend

#93 Improvement commit fields
  github/commit/forms.py
  github/commit/models.py
  github/github/templates/commits/addCommit.html
  github/github/templates/commits/allCommits.html
Labels: backend, frontend, improvment

#94 removed unused closing date field from task
  github/task/models.py
Labels: backend, improvment

#95 Improvement comment file
  github/comment/forms.py
  github/comment/models.py
  github/comment/views.py
  github/github/templates/comments/create-comment.html
  github/github/templates/comments/edit-comment.html
Labels: backend, frontend, improvment

#96 fix overlapping repository tabs
  github/github/templates/wiki/allWiki.html
Labels: bug, frontend

#97 improve comment rendering with attachment link
  github/github/templates/comments/render-comments.html
Labels: frontend, improvment

#98 Test repository
  github/repository/tests.py
  github/repository/tests/__init__.py
  github/repository/tests/test_forms.py
  github/repository/tests/test_url.py
  github/repository/tests/test_views.py
Labels: backend, testing

#100 Test user
  github/github/views.py
  github/user/tests.py
  github/user/tests/__init__.py
  github/user/tests/test_forms.py
  github/user/tests/test_url.py
  github/user/tests/test_views.py
Labels: backend, testing

#101 Test label
  github/label/tests.py
  github/label/tests/__init__.py
  github/label/tests/test_forms.py
  github/label/tests/test_url.py
  github/label/tests/test_views.py
Labels: backend, testing

#102 Improvement test user
  github/user/tests/test_forms.py
  github/user/tests/test_views.py
  github/user/views.py
Labels: backend, improvment, testing

#103 Testing milestone
  github/milestone/tests.py
  github/milestone/tests/__init__.py
  github/milestone/tests/test_forms.py
  github/milestone/tests/test_urls.py
  github/milestone/tests/test_views.py
Labels: backend, testing

#105 Added migrations.
  github/branch/migrations/0001_initial.py
  github/comment/migrations/0001_initial.py
  github/commit/migrations/0001_initial.py
  github/label/migrations/0001_initial.py
  github/milestone/migrations/0001_initial.py
  github/photo/migrations/0001_initial.py
  github/project/migrations/0001_initial.py
  github/repository/migrations/0001_initial.py
  github/task/migrations/0001_initial.py
  github/user/migrations/0001_initial.py
  github/wiki/migrations/0001_initial.py
Labels: backend

#107 Bugfix tests
  github/label/tests/test_views.py
  github/label/views.py
  github/milestone/tests/test_views.py
  github/repository/tests/test_views.py
Labels: bug, testing

#108 Dockerization
  Dockerfile
  Pipfile
  Pipfile.lock
  docker-compose.yml
  github/github/settings.py
  github/templates/base.html
  github/templates/branch/addBranch.html
  github/templates/branch/allBranches.html
  github/templates/branch/detailBranch.html
  github/templates/branch/newBranch.html
  github/templates/comments/create-comment.html
  github/templates/comments/delete-comment.html
  github/templates/comments/edit-comment.html
  github/templates/comments/render-comments.html
  github/templates/commits/addCommit.html
  github/templates/commits/allCommits.html
  github/templates/label/add-label.html
  github/templates/label/all-labels.html
  github/templates/label/delete-label.html
  github/templates/label/render-labels.html
  github/templates/label/update-label.html
  github/templates/landing/landing.html
  github/templates/milestone/addMilestone.html
  github/templates/milestone/allMilestones.html
  github/templates/milestone/deleteMilestone.html
  github/templates/milestone/milestonesInProject.html
  github/templates/milestone/updateMilestone.html
  github/templates/navbar.html
  github/templates/photo/addPhoto.html
  github/templates/profile/profile.html
  github/templates/profile/update.html
  github/templates/project/addProject.html
  github/templates/project/allProjects.html
  github/templates/project/deleteProject.html
  github/templates/project/detailProject.html
  github/templates/project/updateProject.html
  github/templates/registration/login.html
  github/templates/registration/registration.html
  github/templates/repository/addRepository.html
  github/templates/repository/allRepositories.html
  github/templates/repository/detailRepository.html
  github/templates/repository/repoTabs.html
  github/templates/repository/repositoriesHomePage.html
  github/templates/task/all-tasks.html
  github/templates/task/delete-task.html
  github/templates/task/detail-task.html
  github/templates/task/render-tasks.html
  github/templates/task/task-in-project.html
  github/templates/wiki/allWiki.html
  github/templates/wiki/wiki.html
  requirements.txt
  start.sh
Labels: devops

#109 Feature cashing commit
  github/commit/views.py
  github/github/settings.py
  requirements.txt
Labels: backend, devops, feature

#110 Implemented cashing wiki's data.
  github/wiki/views.py
Labels: backend, devops, feature

#111 Created travis.yml.
  github/.travis.yml
Labels: devops

#112 Feature implement ci
  .travis.yml
Labels: devops

#113 Implemented caching for milestone's data.
  github/milestone/views.py
Labels: backend, devops, feature

#114 Implemented caching for project's data.
  github/project/views.py
Labels: backend, devops, feature

#115 Added cashing for label's data
  github/label/views.py
Labels: backend, devops, feature

#116 Remove travis.yml file duplicate
  github/.travis.yml
Labels: backend, bug, devops

#118 Feature authentification
  github/branch/views.py
  github/comment/views.py
  github/commit/views.py
  github/github/settings.py
  github/label/views.py
  github/milestone/views.py
  github/photo/views.py
  github/project/views.py
  github/repository/views.py
  github/task/views.py
  github/templates/registration/login.html
  github/user/views.py
  github/wiki/views.py
Labels: backend, feature

#119 Feature cashing task
  github/task/views.py
Labels: backend, devops, feature

#120 Improve user test
  github/user/tests.py
  github/user/tests/__init__.py
  github/user/tests/test_forms.py
  github/user/tests/test_url.py
  github/user/tests/test_views.py
  start.sh
Labels: backend, testing

#121 Bugfix tests milestone label
  github/label/tests/test_views.py
  github/milestone/tests/test_views.py
Labels: backend, bug

#122 Fix travis test and start file
  .travis.yml
  docker-compose.yml
  start.sh
Labels: bug, devops

#123 Added cashing for comment's data
  github/comment/views.py
Labels: backend, testing

#124 Remove delete button for master branch
  github/templates/branch/allBranches.html
Labels: backend, bug, frontend

#125 Add caching for branch
  github/branch/views.py
Labels: backend, frontend

#126 Make branch name unique
  github/branch/models.py
Labels: backend, bug

#127 Repository and branches final fixes
  github/branch/views.py
  github/repository/tests/test_views.py
  github/repository/views.py
  github/templates/branch/allBranches.html
Labels: bug
